/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kt.server

import io.ktor.application.*
import io.ktor.http.*
import io.ktor.server.testing.*
import kotlin.test.*

class AppTest {

  @Test
  fun testAppGreetingIsHelloWorld() {
    val classUnderTest = App()
    assertEquals(classUnderTest.greeting, "Hello World!")
    println("Test succeeded")
  }

  @Test
  fun testRequests() =
      withTestApplication(Application::main) {
        with(handleRequest(HttpMethod.Get, "/")) {
          assertEquals(HttpStatusCode.OK, response.status())
          assertEquals("Hello from Ktor Testable sample application", response.content)
        }
        with(handleRequest(HttpMethod.Get, "/health")) {
          assertEquals(HttpStatusCode.OK, response.status())
        }
      }
}
