/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kt.server

import io.ktor.application.*
import io.ktor.http.*
import io.ktor.features.*
import io.ktor.response.*
import io.ktor.routing.*
import io.ktor.sessions.*

class App {
  val greeting: String?
    get() {
      return "Hello World!"
    }
}

// fun main() {
//   embeddedServer(Netty, port = 8000) {
//       routing {
//           health()
//       }
//   }.start(wait = true)
// }

fun main(args: Array<String>): Unit = io.ktor.server.netty.EngineMain.main(args)

fun Application.main(testing: Boolean = false) {
  install(DefaultHeaders)
  install(CallLogging)
  routing {
    get("/") {
      call.respondText("Hello from Ktor Testable sample application", ContentType.Text.Plain, HttpStatusCode.OK)
    }
    health()
  }
}
